spring.application.name=personas
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}

# Configuraci\u00f3n del proxy para capturar tr\u00e1fico en Burp Suite
http.proxyHost=botch-parcel-ecosphere.ngrok-free.dev
http.proxyPort=80
https.proxyHost=botch-parcel-ecosphere.ngrok-free.dev
https.proxyPort=443